# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orderDetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_orderDetails(object):
    def setupUi(self, orderDetails):
        orderDetails.setObjectName("orderDetails")
        orderDetails.resize(628, 505)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        orderDetails.setWindowIcon(icon)
        self.skuNameBox = QtWidgets.QLabel(orderDetails)
        self.skuNameBox.setGeometry(QtCore.QRect(10, 10, 91, 31))
        self.skuNameBox.setText("")
        self.skuNameBox.setObjectName("skuNameBox")
        self.statusBox = QtWidgets.QLabel(orderDetails)
        self.statusBox.setGeometry(QtCore.QRect(130, 10, 91, 31))
        self.statusBox.setText("")
        self.statusBox.setObjectName("statusBox")
        self.label = QtWidgets.QLabel(orderDetails)
        self.label.setGeometry(QtCore.QRect(10, 60, 61, 41))
        self.label.setObjectName("label")
        self.addressBox = QtWidgets.QLabel(orderDetails)
        self.addressBox.setGeometry(QtCore.QRect(80, 60, 541, 41))
        self.addressBox.setText("")
        self.addressBox.setObjectName("addressBox")
        self.orderNoBox = QtWidgets.QLabel(orderDetails)
        self.orderNoBox.setGeometry(QtCore.QRect(330, 10, 271, 31))
        self.orderNoBox.setText("")
        self.orderNoBox.setObjectName("orderNoBox")
        self.label_2 = QtWidgets.QLabel(orderDetails)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 61, 31))
        self.label_2.setObjectName("label_2")
        self.wuLiuListBox = QtWidgets.QListView(orderDetails)
        self.wuLiuListBox.setGeometry(QtCore.QRect(10, 151, 611, 341))
        self.wuLiuListBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.wuLiuListBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.wuLiuListBox.setObjectName("wuLiuListBox")
        self.wuLiuNameBox = QtWidgets.QLabel(orderDetails)
        self.wuLiuNameBox.setGeometry(QtCore.QRect(80, 110, 54, 31))
        self.wuLiuNameBox.setText("")
        self.wuLiuNameBox.setObjectName("wuLiuNameBox")
        self.wuLiuNoBox = QtWidgets.QLabel(orderDetails)
        self.wuLiuNoBox.setGeometry(QtCore.QRect(150, 110, 391, 31))
        self.wuLiuNoBox.setText("")
        self.wuLiuNoBox.setObjectName("wuLiuNoBox")
        self.label_3 = QtWidgets.QLabel(orderDetails)
        self.label_3.setGeometry(QtCore.QRect(270, 10, 54, 31))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(orderDetails)
        QtCore.QMetaObject.connectSlotsByName(orderDetails)

    def retranslateUi(self, orderDetails):
        _translate = QtCore.QCoreApplication.translate
        orderDetails.setWindowTitle(_translate("orderDetails", "订单详情"))
        self.label.setText(_translate("orderDetails", "收货地址："))
        self.label_2.setText(_translate("orderDetails", "物流："))
        self.label_3.setText(_translate("orderDetails", "订单号："))
